# Generated by Django 2.2.4 on 2021-03-19 06:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apartsnsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartsnsmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='apartsnsmodel',
            name='good',
        ),
        migrations.RemoveField(
            model_name='apartsnsmodel',
            name='images',
        ),
        migrations.RemoveField(
            model_name='apartsnsmodel',
            name='read',
        ),
        migrations.RemoveField(
            model_name='apartsnsmodel',
            name='readtext',
        ),
        migrations.AlterField(
            model_name='apartsnsmodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apartsnsapp.ApartsnsModel', verbose_name='コメント')),
            ],
        ),
    ]
