# Generated by Django 2.2.4 on 2021-03-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartsnsapp', '0002_auto_20210319_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartsnsmodel',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='投稿者'),
        ),
    ]
